version: "3.7"

services:
  &db-service db_store_ms:
    container_name: *db-service
    hostname: *db-service
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/store_ms
    volumes:
      - pg_store_data:/var/lib/postgresql/data:rw
  &pgadmin-service pgadmin_ms:
    container_name: *pgadmin-service
    hostname: *pgadmin-service
    image: dpage/pgadmin4:latest
    ports:
      - "82:80"
    depends_on:
      - *db-service
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
  &gateway-service gateway:
    container_name: *gateway-service
    hostname: *gateway-service
    build:
      context: ../gateway
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    working_dir: /home/app
    volumes:
      - ../gateway:/home/app:rw
    ports:
      - "3000:3000"
    user: 1000:1000
  &products-service products-service:
    container_name: *products-service
    hostname: *products-service
    build:
      context: ../products-service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    working_dir: /home/app
    volumes:
      - ../products-service:/home/app:rw
    ports:
      - "3001:3001"
    user: 1000:1000
  &customers-service customers-service:
    container_name: *customers-service
    hostname: *customers-service
    build:
      context: ../customers-service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    working_dir: /home/app
    volumes:
      - ../customers-service:/home/app:rw
    ports:
      - "3002:3002"
    user: 1000:1000
  &proxy-service proxy:
    container_name: *proxy-service
    hostname: *proxy-service
    build:
      context: ../proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
  &auth-service auth-service:
    container_name: *auth-service
    hostname: *auth-service
    build:
      context: ../auth-service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    working_dir: /home/app
    volumes:
      - ../auth-service:/home/app:rw
    ports:
      - "3003:3003"
    user: 1000:1000

volumes:
  pg_store_data:
  pgadmin: